markdown: kramdown
highlighter: rouge

google_analytics_id: UA-11372017-15
google_site_verification: jiP2R2ChVswrFQDh4LRw5k5jBfEwbB90ejGhLmkVL7o

repository: https://github.com/sebdi/kalman-filter.de
help_url: https://github.com/jekyll/jekyll-help

timezone: America/Los_Angeles

collections:
  docs:
    output: true
  posts:
    permalink: /news/:year/:month/:day/:title/
    output: true

name: Kalman-Filter
description: Webseite zum Kalman-Filter Buch
url: http://www.kalman-filter.de

logo: /img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - README.md
  - .gitignore
